exports.messageSchema = `
  CREATE TABLE IF NOT EXISTS messages(
    "id" SERIAL PRIMARY KEY,
    "authorId" INT NOT NULL REFERENCES users(id),
    "title" VARCHAR(255) NOT NULL,
    "message" VARCHAR(255) NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
  )
`